### ISSUE TITLE
[Bug]: Labs review

### ISSUE THREAD

**Issue by billietlsfeir** [sfeir-open-source/sfeir-school-github-actions#9]
### Describe the bug

01-GA-Basics : les paragraphes "Let's fix it" et "Bonus" sont les mêmes
02-Interact-With-Env : les deux derniers paragraphes sont vides, et il n'y a pas d'étape pour l'affichage du commit sha-1 (comme annoncé dans l'intro du lab)
03-Reusable-Workflows-solution : le workflow n'utilise pas la vesion de npm passé en entrée

Pour les labs 4 et 6, il n'y a pas de solution ?

### Expected behavior

C'est déjà pas mal

**Comment by bogaertg** [comment]
### Describe the bug

* 01-GA-Basics : les paragraphes "Let's fix it" et "Bonus" sont les mêmes => **Fixed**
* 02-Interact-With-Env : les deux derniers paragraphes sont vides, et il n'y a pas d'étape pour l'affichage du commit sha-1 (comme annoncé dans l'intro du lab)
* 03-Reusable-Workflows-solution : le workflow n'utilise pas la vesion de npm passé en entrée =>  **Fixed**

Pour les labs 4 et 6, il n'y a pas de solution ?

### Reproduction steps

_No response_

### Expected behavior

C'est déjà pas mal

### Screenshots

_No response_

### System information

_No response_

### Additional context

_No response_
